# Generated by Django 6.0.6 on 2026-10-06 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_alter_todo_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='task',
            field=models.CharField(max_length=200),
        ),
        migrations.AddConstraint(
            model_name='todo',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('task',), name='unique_active_task'),
        ),
    ]
